
export const UI_TEXTS = {
  gameTitle: "Juego Interactivo: Contratación Pública Justa",
  subtitle: "Aprende sobre el Art. 70 LCSP y la igualdad en licitaciones",
  startGame: "Comenzar Juego",
  next: "Siguiente",
  continue: "Continuar",
  consultAdvisor: "Consultar Experto IA",
  askAdvisor: "Preguntar al Experto",
  advisorPlaceholder: "Escribe tu pregunta sobre el Art. 70 LCSP aquí...",
  close: "Cerrar",
  score: "Puntuación",
  scenario: "Escenario",
  decision: "Decisión",
  keyConcept: "Concepto Clave",
  reference: "Referencia Guía",
  correct: "¡Correcto!",
  incorrect: "Respuesta Incorrecta",
  finalScore: "Puntuación Final",
  playAgain: "Jugar de Nuevo",
  gameEndMessage: "¡Felicidades! Has completado todos los escenarios.",
  gameEndSummary: "Esperamos que este juego te haya ayudado a comprender mejor los principios y procedimientos del Artículo 70 de la LCSP para garantizar una contratación pública justa y transparente.",
  loadingAdvisor: "Consultando al experto IA...",
  advisorUnavailable: "El Asesor IA no está disponible en este momento.",
  scenarioConclusion: "Conclusión del Escenario",
  welcomeTitle: "Bienvenido/a al Juego de Contratación Pública Justa",
  welcomeMessage: "Este juego te guiará a través de escenarios basados en la 'Guía para Evitar Ventajas Indebidas de Licitadores con Participación Previa'. Tu objetivo es tomar decisiones que aseguren la igualdad y transparencia en la contratación pública, conforme al Artículo 70 de la LCSP. ¡Buena suerte!",
  generalPrinciples: "Principios Generales Art. 70 LCSP: Igualdad, Transparencia, Proporcionalidad, Integridad.",
  advisorPopupTitle: "Asesor Experto IA (Gemini)",
  feedbackPopupTitle: "Resultado de tu Decisión",
  scenarioProgress: "Escenario {current} de {total}",
};
